### ISSUE TITLE
Sorting on Grid Columns ADA Review

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1535]

**Comment by maj-stella** [comment]
Figma: https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=827-9904&t=RmPudO13F490qMYo-0 
Storybook: http://localhost:6006/?path=/story/data-grid-data-grid--client-side-sort

**Comment by maj-stella** [comment]
Please could you provide me with Accessibility Sorting Column spec. I can't find it in https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=827-9904&t=RmPudO13F490qMYo-0 Thanks

**Comment by dplsek** [comment]
@maj-stella I've added the ADA spec here:
https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=3509%3A135286&t=tPxOvxUmxVx4cVsf-1

Please let me know if additional ADA considerations need to be captured.

**Comment by maj-stella** [comment]
Hi @dplsek,

Thanks for putting sortable columns in Figma.

One recommendation regarding visible sortable graphic. There is no indication that columns are sortable. This could be confusing if the table row is long and not every cell is sortable. You would need to hover each cell to see if it’s sortable or not. 

Here are some examples how others have designed a visual indicator:

1. Dequee: https://dequeuniversity.com/library/aria/table-sortable

Please notice the graphic how close is to the text. This is because people with magnification software might have difficulties to perceive the graphic is placed too far from the text.

![Image](https://user-images.githubusercontent.com/112501956/234001584-6bfcc494-2858-4222-b205-a4827ea3c28c.png)



2. Adrian Roselli: https://adrianroselli.com/2021/04/sortable-table-columns.html

Please notice again how close he puts a graphic indicating sortable column. Also he enhances the visibility of currently sorted column with a background colour.

![Image](https://user-images.githubusercontent.com/112501956/234001659-729c271f-6c58-495f-9606-d3fcb1232d11.png)

**Comment by bhoppers2008** [comment]
@feliciackh @dplsek this issue is still open. The prod component doesn't include the icon solution in Darrin's updated spec link above. (cc' @joshwooding )

**Comment by dplsek** [comment]
There's actually a set of sorting icons in the Salt library which are not in UITK. The logical choice would be to use them instead of the up/down arrows as currently shown in the design. However, can the column header be configured to know if the column contains numbers or letters? Because there are actually two sets of icons that are dependent on this to know which to display:

Sort alpha ascend
Sort alpha descend
Sort num ascend
Sort num descend

https://storybook.saltdesignsystem.com/?path=/docs/documentation-icons-icon--page

If this can be done, we should use these and i will update the design accordingly.

**Comment by dplsek** [comment]
Cool. will wait for dev to confirm if we can detect column type. 

Re: generic icon arrow up/down... i think we just use the alpha/num ascend icon on hover/focus (depending on column type) and then it sticks on click, then switches to descend on click again, and on click-again goes back to ascend (on hover). not sure what the difference is between using these or generic arrows that are indicating the same thing?

**Comment by feliciackh** [comment]
@dplsek @bhoppers2008 It's possible to determine type of data, it'll involve a bit of refactoring in current code

cc @joshwooding
