### ISSUE TITLE
Toggle Button Group should not open empty tooltip

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#179]
Although there is `disableTooltip` prop available, but this shouldn't be necessary for a text only group which shouldn't raise any accessibility concern

![Empty tooltip](https://user-images.githubusercontent.com/5257855/173066858-2a34824b-ef63-42f3-a12a-dbd3bf5c2f51.png)

Reproduce: https://react-ts-vvs62w.stackblitz.io

**Comment by GH-aditya** [comment]
i can fix this

**Comment by GH-aditya** [comment]
assign me

**Comment by hardik1805** [comment]
Can you please this task to me so I can make my contribution to this project?

**Comment by joshwooding** [comment]
Hi @GH-aditya and @hardik1805 thank you both for your enthusiasm. We're currently doing a refactor for Tooltip, which would affect this work. It would be best for that work to finish before looking at this. Once this issue is picked up, I'll add a comment here. In the meantime it would be worth you reading our [Contribution guidance](https://github.com/jpmorganchase/.github/blob/main/CONTRIBUTING.md) we have a CLA that will need to be filled out and submitted before we can accept your changes.

Thanks

**Comment by joshwooding** [comment]
This will be tackled in the refactor PR #1682
