### ISSUE TITLE
Site Utilities Library

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#1916]
Creating Salt Site Utilities Library, equivalent to Salt Spec Utilities: https://www.figma.com/file/i8kSFpGbHIWXnv6LFvWKdU/Salt-Spec-Utilities?type=design&mode=design&t=NfBcCGpE9XLZ5AKi-0

The Site Utilities library are the components used to create pages with spec documentation which are consistent in appearance and layout for Salt site.

**Comment by yunjungyeh** [comment]
🟠30 June - build components for Site utilities
🟠29/30 June - Analysing the built site and the design in Figma files (to define the spec of components)

**Comment by james-nash** [comment]
I'm a little unclear (and curious) about what the goal of this issue is.

1. Is the intent to create a Figma library of site components (e.g. page header, footer, example containers, image switcher, etc.)?
2. Or, is this a customized version of the spec utilities?

If it's the former, then can I ask that you liaise with me? I can explain what components we have implemented in code, since it would make sense to align their Figma counterparts. Also, @shey-v's original Figma designs for the Salt site are likely to contain component designs you could extract and reuse. Btw, I'm hoping to produce some team-internal component doc pages for the existing site components, so that would be another thing to align (or collaborate?) on.

If it's the latter, I'd be interested to understand what differences you anticipate compared to the generic Salt spec library? I.e. what extra or different things might a designer need when annotating a design for the Salt website versus for the Sal component libraries?

**Comment by yunjungyeh** [comment]
Thank you for raising it @james-nash 
Should be the first one, I will schedule a call with @shey-v @bhoppers2008 to see how we can use what we've had and collaborate.

**Comment by james-nash** [comment]
Cool. Could you include me in that call too, please?

**Comment by bhoppers2008** [comment]
@james-nash fyi I asked @yunjungyeh to quickly pull together a library based on the forms pattern page i've built, in order to help put together the International Address Pattern page. At this stage, that's the primary goal, with the secondary goal of having a library designer's can use to create these pages quickly. If there are more that Yun can extract from @shey-v 's work then that's brilliant but i know the one's i've built are representative having worked with Josh and a quick start for Yun :)

**Comment by james-nash** [comment]
@bhoppers2008 Thanks for the clarification. Makes sense. Might be a good idea to update this issue's description then.

I think it may still be worth us all having a quick chat. For any new site pages/seciton I'm keen for us to maximize reusing things we already have and minimising "special snowflake" components. I think if we can start collating the available components somewhere, so that they're discoverable and somewhat documented for the next person who wants to add a new page or section, that'll go a long way to that end.

It can (and at this point, probably _should_) lean and scrappy. Maybe a Figma shared library where we can "dump" things we've already made, which the team can then use and add to/refine over time. As mentioned above, I'd like to do something analagous with the React components - i.e. use our component page template to write up some basic docs and examples, which we can then surface in a secret section of our site.

**Comment by yunjungyeh** [comment]
@james-nash no problem would include you as well! For now I would focus on getting International Address Input pattern done as pattern page is the first priority. Then we can sync and collaborate - will schedule some time possibly next week, thanks!

**Comment by shey-v** [comment]
Thanks for looking into this @yunjungyeh - it would be brilliant to have a library specifically for patterns, I started some research and initial mockups in Figma https://www.figma.com/file/luPB1hhmKO8UKfhzgipK9D/Site---Birthday-cake%3A-Patterns-documentation?type=design&node-id=1%3A3482&mode=design&t=kXbel5RIyeb0cDBO-1 a while ago, if you need to reference it :)

**Comment by yunjungyeh** [comment]
✅5/6 July - sort out new components in Components template
✅30 June/3-4 July - build components for Site utilities
✅29/30 June - Analysing the built site and the design in Figma files (to define the spec of components)
