### ISSUE TITLE
Tooltip not displaying correctly inside Form Field when validation status is empty string

### ISSUE THREAD

**Issue by tejasnikam** [jpmorganchase/salt-ds#2752]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.8.0

### Description

Tooltip not displaying correctly when it is wrapped inside `FormField` with empty validation status. While it works as expected when used independently.

### Steps to reproduce

```
import { FormFieldLabel, Tooltip, FormField } from "@salt-ds/core";
import { InfoIcon } from "@salt-ds/icons";
import "@salt-ds/theme/index.css";

export default App = () => {
  return (
    <FormField validationStatus={""}>
      <FormFieldLabel>
        {"FormField Label"}
        <Tooltip
          content={"Testing Tooltip"}
          hideIcon={true}
          placement={"bottom"}
          hideArrow={false}
        >
          <InfoIcon />
        </Tooltip>
      </FormFieldLabel>
    </FormField>
  );
};

```

### Expected behavior

Tooltip Arrow should not break as well as border should be consistent and should only be depend upon tooltip status

### Operating system

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Hi @tejasnikam sorry for the delay. This issue is because when validationStatus is set to "" on FormField this line 
https://github.com/jpmorganchase/salt-ds/blob/90d3a24236d10ad72dbc47a9bddb309ad5f6a1e0/packages/core/src/tooltip/Tooltip.tsx#L93
resolves to an empty string due to the `??` operator. 

Could I ask why `""` is being used instead of `undefined`? `""` isn't allowed by the types and using `undefined` won't have this issue and is the intended usage.

We could always update this check to be more defensive

**Comment by joshwooding** [comment]
Although, an invalid form validation status is being used here, the component shouldn't break as badly. @tejasnikam do you mind contributing a fix for this?
