### ISSUE TITLE
Provide alternative icon to Toast

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3088]
### Area

UI Components

### The problem

I want to implement something like this using Toast, when user clicks a copy button

![example toast with link icon](https://github.com/jpmorganchase/salt-ds/assets/5257855/9bcd0a3f-4069-4422-9e2c-44eb87c62bc8)

### The solution

Alternative icon for Toast

### Alternatives and examples

Target  `.saltToast-icon.saltIcon` with `display:none` and put link icon together with content

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by nathanmmiller** [comment]
Quick proposal: I would say the most versatile way to support this would be to allow StatusIndicator to take an optional "icon" prop (typed as React.ElementType<IconProps>) that, when provided, is what is used for "IconComponent" rather than looking up the icon in the "icons" object. 

This could then be a prop on Toast as well, simply passed through to the underlying StatusIndicator.

**Comment by joshwooding** [comment]
An alternative approach is to align with our upcoming Tooltip work cc @bhoppers2008, which would be to offer a "status-less" option which would then not have an icon making it easy to swap out and would probably fit in better with a custom "type" of toast.

**Comment by nathanmmiller** [comment]
> An alternative approach is to align with our upcoming [Tooltip work](#3091) cc @bhoppers2008, which would be to offer a "status-less" option which would then not have an icon making it easy to swap out and would probably fit in better with a custom "type" of toast.

This is similar to what I currently do to achieve the same, which is to use css to hide the existing icon (and which is what caused @origami-z to raise this issue, I believe). However, I actually wouldn't want to have a "status-less" solution for this because it removes the possibility of still having the colorful border for free.

In essence, what I end up with is a custom icon AND a status-related border.

**Comment by origami-z** [comment]
> In essence, what I end up with is a custom icon AND a status-related border.

If you need colored borders, let's go with swapping icon, it comes with built-in spacing / alignment benefit
