### ISSUE TITLE
Provide a mechanism to swap out built-in component icons to custom icons

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3520]
To support adoption, need to a way to swap out built-in icons, e.g. icons in status indicator, chevron in accordion

- API (e.g. start with a separate Provider implementation, later to decide whether to merge with `SaltProvider`)
- Full list of names and default value documented
- Custom icon requirement (e.g. have to use Salt icon generation script? is it just `--icon-color` in `Icon.css`?)

Example (not to be final API), from user point of view

```
import {CustomErrorIcon} from '@another-library/icon';

const customMapping = {
   error: CustomErrorIcon
  // expand, collapse, submenu, status (error/warning/success/info), overflow, user profile
};

<SemanticIconProvider value={customMapping}>
```

Icon provider should fill in fallback icon, i.e., all other icons will be default to Salt icons.
All components using error icon (e.g. StatusIndicator) will be using `CustomErrorIcon`. 

From Salt internal perspective, it will be something like 

before:
```
// e.g. in dropdown
<ChevronUpIcon aria-hidden />
```

after:
```
// useSemanticIcon, the hook will get either a custom icon passed in or default Salt icon
const SemanticExpandIcon = useSemanticIcon("expand"); 

<SemanticExpandIcon aria-hidden />
```

Questions:

1. Is it possible to make different component to pick different icons? e.g. Dropdown's expand/collapse icon v.s. Accordion expand/collapse icon, what if a user want to only swap out Accordion expand icon not Dropdown. Possibly related to #3939
    1. Audit differences between DS, same semantic icon used in different components? e.g. Accordion vs Dropdown case
1. Is it possible to change icon color in a component via custom icons? e.g. Accordion chevron to use a different color than Salt ones.

----

Design in #3625

https://www.figma.com/design/xET9vAEtgJ7w29lGNGAcrF/Salt-(Next)-Iconography?node-id=41-2264&t=8DBsM4nqta9xP3Vb-1

**Comment by pseys** [comment]
FYI @bhoppers2008

**Comment by mark-tate** [comment]
Goal: 
by EOS have a plan for the approach

**Comment by origami-z** [comment]
Aug 12 - will start later in the week

**Comment by joshwooding** [comment]
Aug 14 - Working on the mappings.

**Comment by joshwooding** [comment]
Aug 20 - ready for review

**Comment by origami-z** [comment]
Blocked by icon naming confirmation, which was thought to be done in #3625 (but was rescoped to Figma work)

**Comment by bhoppers2008** [comment]
@bhoppers2008  to send Vineet semantic icon names for build. Can review once updated. @pseys

**Comment by origami-z** [comment]
Caught up with @Vineet119 
- Only include Salt's icon name (not include additional ones needed from Pepper). It's easier to add more if Pepper's design desire for different icons (e.g. dropdown vs accordion) is justified for Salt to support.
    - Need to ask Pepper designer to provide why different icons are needed
- Wait @pseys back to update missing names (e.g. calendar, sub-menu chevron icon, etc.)

**Comment by origami-z** [comment]
Salt / Pepper icon difference audit link -
https://www.figma.com/design/6yIx5tpSk2y1b4alYaifi2/Pepper-workspace?node-id=395-6227&t=MXYz08aI3q0Cf7rs-1

**Comment by mark-tate** [comment]
Espresso Goal: design to unblock themselves, feature released by 13th September

**Comment by bhoppers2008** [comment]
@origami-z @Vineet119 the design guidance is linked to this issue here: https://github.com/jpmorganchase/salt-ds/issues/3625#issuecomment-2306764388

@pseys we need a plan for what we do with this information.

**Comment by mark-tate** [comment]
Frappe Goal: agree names and publish/release by EOS

**Comment by mark-tate** [comment]
call on Tue, to agree names

**Comment by mark-tate** [comment]
Call now on Wednesday

**Comment by origami-z** [comment]
Summary of meeting 

- Reviewed naming, updated some, e.g. step ones
- Split chevrons into multiple semantic icons, e.g. dropdown vs menu vs pagination chevron are different
- Identified potential break of semantic on nested horizontal navigation item chevron (expand/collapse both down), can workaround for now but should be looked at in #2405 
- Exclude check mark (in checkbox and switch) from the set, which can be always added in more when needed. It would be impacted by #4100, and it's not blocking Pepper adoptoin


Paul to share Figma design later

**Comment by pseys** [comment]
Semantic naming review complete and final list agreed on 25 Sept. Due to changes proposed to success icons it was agreed to omit the icons used in Checkbox and Switch from this piece of work. The agreed semantic icon names are as follows: 

| SemanticIconProvider | Salt Icon | Component | Usage |
| --- | --- | --- | --- |
| `expand` | `chevronDownIcon` | Accordion, ComboBox, Dropdown | |
| `collapse` | `chevronUpIcon` | Accordion, ComboBox, Dropdown | |
| `expandGroup` | `chevronRightIcon` | Menu Item, Navigation Item | Variant: Vertical, State: Collapsed |
| `collapseGroup` | `chevronDownIcon` | Navigation Item | Variant: Vertical, State: Expanded. Variant: Horizontal, State: Expanded, Collapsed |
| `next` | `chevronRightIcon` | Pagination | |
| `previous` | `chevronLeftIcon` | Pagination | |
| `increase` | `triangleUpIcon` | Stepper Input | |
| `decrease` | `triangleDownIcon` | Stepper Input | |
| `close` | `closeIcon` | Dialog, Drawer, Overlay | |
| `info` | `infoSolidIcon` | Status Indicator | |
| `error` | `errorSolidIcon` | Status Indicator, Stepped Tracker | |
| `warning` | `warningSolidIcon` | Status Indicator, Stepped Tracker | |
| `success` | `successTickIcon` | Status Indicator | |
| `pending` | `stepDefaultIcon` | Stepped Tracker | |
| `active` | `stepActiveIcon` | Stepped Tracker | |
| `completed` | `stepSuccessIcon` | Stepped Tracker | |
| `overflow` | `overflowMenuIcon` | ComboBox, Tabs | |
| `external` | `tearOutIcon` | Link | |
| `upload` | `uploadIcon` | File Drop Zone | |
| `calendar` | `calendarIcon` | Date Picker | |
| `user` | `userSolidIcon` | Avatar | |

**Comment by origami-z** [comment]
Very minor, Looking at 2 expands, is there a need to name expand to something like "expand content"

**Comment by mark-tate** [comment]
can we document somewhere our strategy for naming so when we add an icon, anybody can do it and we maintain the conventions we have used here.
ie. functional names preferred for actions, presentational names for adornments
Example of good/bad maybe a good way to approach it,
ie. don't call an action, downArrow, because  that the semantics represent the action, not the icon, call it expand
We could add considerations like, RTL

**Comment by origami-z** [comment]
> can we document somewhere our strategy for naming so when we add an icon, anybody can do it and we maintain the conventions we have used here.

Yes, i think Paul is aware of the existing naming deviation. We need to define a plan for us to get out of this, likely needing to form a migration / deprecation path.

With this semantic icon name work / discussion, we would have discovered most of the internal icon usage issues, so we can address them over time.
