### ISSUE TITLE
Theme: Icon switching

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#3625]
EOS: Approved approach to swapping Icons in Salt (Next) Figma library.

**Comment by pseys** [comment]
### POC 1

Concept: Create 'semantic icon' component
Outcome: 
- 👍 Works as expected – provides the ability for a designer to select the icon component and switch icon libraries for a limited number of semantically mapped icons
- 👎Put the effort onto the core design team – any future libraries or additional semantic mappings needed would require the core design team to add them into the component library
- 👎Icons can only be changed on a case by case basis – each icon within a design would need to be manually swapped if a different library is needed, including status icons, dropdown chevrons, etc. 
- 👎 No way to set a default library or control with variables

### POC 2

concept: Add 'semantic icons' to existing Salt icon library and enable library swapping in Figma
Outcome: 
- 👍 semantic icon collection created
- 👍 second (test) icon library with icons mapped to same semantics created
- 👍 swapping libraries allows designers to swap all icons in a file with one action
- 👎 library swap would need to be carried out periodically, as newly added components would revert to the original icon library
- 👎 In POC library swap failed - 
- 👎 Figma won't recognise/swap nested icons – as icons are mostly contained within the icon component this prevents us from adding the ability to swap libraries 

### Summary

Option 2 seems to be the better solution, however, additional work needs to be carried out to the component library and icon library to test further. 

- Icons in the icon library need to be changed so that their base size (W/H) are derived from a variable: `size-icon`
- Icons in the icon library need to be changed so that their base colour is derived from a variable: `content-primary-foreground`
- Nested icons within the Salt (Next) component library need to be changed from the icon component to icons directly from the Salt icon library

Once these tasks have been completed a follow-up POC can be run.

**Comment by mark-tate** [comment]
Goal: 
Icon Library - change width/height color of all icons S(3)
Nested Icons -  need to be changed from the icon component to icons directly from the Salt icon library

**Comment by pseys** [comment]
> Goal: Icon Library - change width/height color of all icons S(3) Nested Icons - need to be changed from the icon component to icons directly from the Salt icon library

I've created an issue for the first goal #3628

**Comment by bhoppers2008** [comment]
Investigate if we need the icon and country symbol at all (in the Salt Next library) or can we control the scaling using the figma only variables.

**Comment by navkaur76** [comment]
Updates complete in figma branch. Awaiting final decision from @bhoppers2008  on whether we want to remove status indicator component alongside icon component + country symbol.

**Comment by origami-z** [comment]
> Updates complete in figma branch. Awaiting final decision from [@bhoppers2008](https://github.com/bhoppers2008) on whether we want to remove status indicator component alongside icon component + country symbol.

Is "semantic icons" the approach in the branch?

**Comment by navkaur76** [comment]
22/07 - meeting w/ Ivan, Yun + Paul

**Notes (vertical stepped tracker icon usage):**

- Stepped Tracker consideration: the latest stepped tracker design consists of a vertical variant which contains Steps and Sub-steps. Steps use (1.5x) icons, and sub-steps use (1x) icons (with both referencing the Icon component). Steps can be configured to display either (1.5x) or (1x) icons as an option for users to maintain legacy sizing. Nested component structure means the Icon component is currently needed to display (1.5x) in Step. Also, icon sizes cannot be configured directly via variables when nested. 
- It is not recommended to use alternative icon sizes aside from (1.5x) and (1x). 
- Decision: agreement that this isn't a strong enough justification to keep icon component in Salt (Next) library, since this is a use case unique to only vertical stepped tracker. 
- Instead, @ivan-calderon to explore expanding the Step variant into two items (i.e. Step (1.5x) and Step (1x)), providing users with the ability to switch between either. This avoids nesting the Icon component + exposing unnecessary icon sizes in the props panel. 

Awaiting final feedback from @bhoppers2008 before we can merge icon switching updates.

**Comment by navkaur76** [comment]
Icon switching update to go ahead. Nav to pick back up on 30/07 after AL, and work with Yun to review + merge the figma branch.

**Comment by navkaur76** [comment]
Icon groupings for easier branch merging management (@yunjungyeh) : 

Branch 1: Accordion
Branch 2: Avatar, Banner, Calendar, Checkbox 
Branch 3: Content swap, Dialog, File drop zone, Listbox
Branch 4: Menu, Nav item, Stepped tracker, Switch
Branch 5: Tabs, Toast, Tooltip
Branch 6: Data grid
Branch 7: Form field
Branch 8: Contact details, Content status, Metric

**Comment by bhoppers2008** [comment]
I believe there are two parts to this (at least for designers)... this first part was simplifying the implementation of icons in the Next library... that's been merged but is waiting to be published (most figma releases are blocked by button atm) @yunjungyeh 

The second part is @pseys (and @origami-z ) documenting the recommended approach for icon swapping with Salt. I would expect design and dev alignment on this (or at least acknowledgement on how both acheive it). In Figma, at least for now, it's on a case by case, component by component (in consumer designs or extension libraries) basis. 

It's currently documented ⁠[here](https://sites.jpmchase.com/:w:/r/sites/JPMUIToolkit/Shared%20Documents/General/Theme/Icon%20swapping.docx?d=wee3eee74238c4183afa6431a8b810f9e&csf=1&web=1&e=VFKP4d) but would ideally be moved into a visible place.
