### ISSUE TITLE
Drawer update document around modal only recommendation

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3818]
### Area

UI Components

### The problem

Drawer currently only supports overlaying entire screen. There are use cases where this should not cover the entire screen, e.g. drawer should not overlay app header. 

### The solution

Provide a mechanism to target certain container for the drawer and scrim to show up.

Need to work out accessibility implication 

### Related to 

- #3968
- #3252 

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
Rather than build in Salt, add some docs to our site to explain the recommended alternatives ?
@mark-tate  close and replace with new documentation ticket

**Comment by mark-tate** [comment]
Cortado Goal: call to discuss alternatives and then add docs to site

**Comment by jake-costa** [comment]
ADA Feedback:
To make this work, we need to:
Remove aria-modal.
Remove the focus trap.
Reflow content so that it is not overlapped by the drawer when open and ensure appropriate focus order **or** have the drawer collapse when focus leaves the drawer.

Recommendation:
Instead of modifying the drawer component, I recommend using the side panel component. This approach addresses the request more effectively.

**Comment by origami-z** [comment]
Aug 16 - 2 steps
1. document feedback above
2. create a ticket for non-model drawer for future prioritize
