### ISSUE TITLE
Floating filter items are center aligned in ag-grid 31.3.1

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3877]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Description

Ag grid has reportedly changed the styling of the floating filter items in v 31.3.1. This makes all items center aligned.

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
Cortado Goal:
Known position, maybe able to close

**Comment by origami-z** [comment]
This is only happening when custom cell renderer is used (therefore not appearing in any of Salt examples), due to below ag grid change/

https://github.com/ag-grid/ag-grid/commit/51ba16931ec3b5160968979aef37f78dce0cf89d

The team raised this should report to ag grid as a bug instead.

---

Temporary remediation 

```css
.ag-set-filter-item-checkbox {
    width: unset;
}
```
