### ISSUE TITLE
Design system website

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/salt-ds#483]
By 14. December, we need to ship an Odyssey website in order to support the initial batch of React components we'll be releasing at the same time. This issue is an ☂️ umbrella for the various tasks that will make that happen.

The main requirements for this V1 "cupcake" site[^cupcake] are:

* Be publicly accessible
* Explain what Odyssey is
* Explain to developers & desginers how to integrate Odyssey into their projects and begin using the available components
* Explain how and where to get help, report bugs, etc.

(#513 will define this in more detail, so please post thoughts & feedback on this outline in the comments on that issue)

- [x] #510
- [x] #513 
- [x] #518 
- [x] #519 
- [x] #534
- [x] #535 

[^cupcake]: The "cupcake" name comes from a cake analogy @shinytoyrobots has used. The "birthday cake" website will be a comprehensive design system website (akin to the ones other popular design systems have). The "wedding cake" website will be a super-amazing site that goes beyond what's considered the norm and becomes the envy of design system people around the world. That makes this first iteration of the site that we're working towards right, the "cupcake" site! 🧁

**Comment by james-nash** [comment]
Here's copy of my _draft_ outline. These are some pages and content for each that I think we ought to consider. However, this is very much a starting point to spark discussions and be refined.

### Homepage

Must clearly convey the following information to visitors:

* What is this?
    * It's a design system for J.P. Morgan (JPM) Corporate & Investment Banking (CIB) business. Enables accessible, coherent, on-brand user experiences. Faster time to market. etc. etc. - the usual DS spiel.
* Who is this for?
    * It's for JPM staff and external partners who are designing and/or building digital experiences that will be JPM-branded and used by CIB staff or clients (double-check this is correct)
* How do I use it?
    * Links to: Overview, getting started, components, support, etc.

### Overview

High-level overview of what this DS provides and how it hangs together

* The key parts (what does it give you)
    * This docs site
        * React component lib
        * Figma lib (will this be public by December? If not, maybe omit it for now or say "coming soon"
    * Features (why should you care?)
        * Small footprint (due to minimal 3rd party deps)
        * 4x densities + light/dark modes
        * Striving for WCAG 2.1 AA compliance
        * Theming
        * Strong pedigree (see history) & battle-hardened design (since it's basically the same as UITK's design - see next point)
    * History (trust us, we know what we're doing!)
        * Successor to JPM's internal-only "JPM UI Toolkit" (aka "UITK") - 4.5yrs old & used across 1200 apps

### Getting started

* As a team
    * How to pitch using Odyssey to your superiors
    * Advice on how design & dev are expected to collaborate using Odyssey?
    * Advocate regularly upgrading as new Odyssey versions come out?
    * How to keep up-to-date? (do we need an RSS feed or a public mailing list perhaps?)
    * Where to get help, request features, make contributions, raise bugs, etc. → link to help page
* As a developer
    * Pre-requisites:
        * Know-how:
        * HTML, CSS & JS fundamentals.
        * React fundamentals.
        * Accessibility fundamentals.
    * Tech: Node vXX + your favourite IDE
        * Project setup
        * NPM packages to install
        * Setting up toolkit provider at root of your app
        * Example of importing some components and links to component docs for further reading
* As a designer (unless this is just "coming soon")
    * Pre-requisites:
        * Familiarity with Figma
        * Interaction design fundamentals
        * Accessibility fundamentals
     * Library setup
        * How to find and use our library/-ies in Figma

### Components

Link over to Storybook for now.

We probably need to tidy up the IA in Storybook though so that it doesn't overlap / conflict with what's in this site

### Support

How & where to:

* Ask for help
* Report bugs
* Suggest features
* Discuss contributions

Likely all of these will link to various places on Github (e.g. specialised issue templates)


### News

Some kind of feed for announcements (new releases, etc.) and blog posts. Could maybe use an external service like Medium for starters and integrate properly into our site at a later date?

**Comment by shinytoyrobots** [comment]
This seems like a solid overview. We may need to pare down somewhat for initial alpha/beta release, but that's fine. We can consider a "fresh start" IA, using some of the research and metrics we already have available, as well as best in class examples in the public domain.

Of the above, I think we can likely minimize the "as a team" part of Getting Started initially (though it will become an important part of the content).

**Comment by shinytoyrobots** [comment]
Must have configurable navigation - e.g. via gatsby-config file (https://www.gatsbyjs.com/docs/creating-dynamic-navigation/), or (as outlined by Carbon's Gatsby theme) with a .yaml file - https://gatsby.carbondesignsystem.com/guides/navigation/sidebar/.

**Comment by james-nash** [comment]
All tasks listed here have been completed and the V1 site is now live 🎉
