### ISSUE TITLE
Identify SEO keywords to target

### ISSUE THREAD

**Issue by JohannaJoergensen** [jpmorganchase/salt-ds#617]
It would be good to know if there are certain search terms / keywords we would like to rank highly for in web searches.

Knowing those can influence our writing (e.g. we can try to use those words / phrases more frequently in the text). While they may also influence descriptions and keywords we put into our `<meta>` tags, it's worth nothing that [those don't really provide any SEO benefit](https://ahrefs.com/blog/meta-keywords/).

**Comment by zdxd** [comment]
@james-nash what is status of issue? doesn't seem like research can help much

**Comment by james-nash** [comment]
Yeah, I think you're right. This will be more of a content team job. I'll update the labels to reflect that.

In terms of status, it's still just lurking on the backlog. I suspect SEO optimization isn't a high priority right now given that we don't (yet) have a lot of content. However, I'll have a chat with the content team to get their advice and views on that.

@mikearildbrown ☝️ FYI, this issue was raised a long time ago. I think it could still be a relevant thing to do at some point, but perhaps it's worth us sitting down at some point to discuss our broader SEO strategy and what the site needs in order to support that.
