### ISSUE TITLE
Initial branding

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#696]
Establish initial Salt branding, so that we can produce visuals for our initial website. We will create a separate ticket in the future to revisit the overall Salt branding and evolve/expand things as needed.

- [x] Create the story of the Salt brand (what is the link between Salt and JPM rationale)
- [x] Create a main graphic
- [x] Create with simple version for our favicon
- [x] Come up with some reusable branding assets
- [x] Create the logo ‘Salt by JPMorgan’ or 'Salt Design System by JPMorgan'

**Comment by shey-v** [comment]
I have a meeting with the design leads, Rufaro and Robin today at 5pm to discuss above and discuss the branding direction.

**Comment by james-nash** [comment]
Slightly rephrased this issue so that it covers the work that was already done for the v1 website.

Given that any further evolution / expansion of the Salt brand is likely to be a broader piece of work, it should be tracked by a new issue.

Therefore closing this one as all the tasks have already been done.
